encryption = "age"

[age]
identity = "~/.config/chezmoi/key.txt"
recipient = "age1vasrepa60hhqt3283pnu25hz8p5jkr82j4w0usaumls7xju7630qunkwsw"

[data]
email = "konecnyallan@gmail.com"
name = "allan"
github_user = "Zillordo"
