[tools]
go = "latest"
node = "latest"
pnpm = "latest"
biome = "latest"
"aqua:biomejs/biome" = "latest"

[tasks]
opensearch_perm = "mkdir -p ./raptor/raptor_filesystem/opensearch-data/ && sudo chown -R 1000:1000 ./raptor/raptor_filesystem/opensearch-data/"
