[tools]
node = "22.18"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:eslint" = "latest"
"npm:nx" = "latest"
television = "latest"
uv = "latest"

[tasks]
dev = "cd ./fidoo-fx-fe && npx nx run bw-react-app:serve"
storybook = "cd ./fidoo-fx-fe && npx nx run storybook-host:storybook"
